apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/webapp.yaml

namePrefix: "user02-"

images:
  - name: "nginx"
    newName: "nginx"
    newTag: "1.27"

labels:
  - pairs:
      app.kubernetes.io/owner: "user02"
    includeSelectors: true
