apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: web
spec:
  stripPrefix:
    prefixes:
      - /user01
      - /user02

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.tls: "false"
    traefik.ingress.kubernetes.io/router.middlewares: zyproj-web@kubernetescrd
  name: web
  namespace: zyproj
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: user01-web
            port:
              number: 8081
        path: /user01
        pathType: Exact
  - http:
      paths:
      - backend:
          service:
            name: user02-web
            port:
              number: 8081
        path: /user02
        pathType: Exact