apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webapp.yaml

namePrefix: "user01-"

labels:
  - pairs:
      app.kubernetes.io/owner: user01
    includeSelectors: true

images:
- name: zy-app
  newTag: 31a59cf
