apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- webapp.yaml
  
namePrefix: user##-

images:
- name: nginx
  newName: registry.ntnxlab.local/library/sample-webapp
  newTag: user##-abcdefg

commonLabels:
  app.kubernetes.io/owner: user##

replicas:
  web: 1
