apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- webapp.yaml
  
namePrefix: user##-

images:
- name: nginx
  newName: rhapsody008/sample-webapp
  newTag: user##-abcdefg

commonLabels:
  app.kubernetes.io/owner: user##
