apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webapp.yaml

namePrefix: "user##-"

labels:
  - pairs:
      app.kubernetes.io/owner: user##
    includeSelectors: true

images:
- name: myapp
  newName: rhapsody008/sample-nodejs-webapp
  newTag: user##-abcdefg
